export const GameActions = {

    MOVE_PLAYER: "MOVE_PLAYER",

    ENTER_DUNGEON: "ENTER_DUNGEON",
    EXIT_DUNGEON: "EXIT_DUNGEON",

    START_COMBAT: "START_COMBAT",
    PLAYER_ATTACK: "PLAYER_ATTACK",
    ENEMY_ATTACK: "ENEMY_ATTACK",
    END_COMBAT: "END_COMBAT",

    OPEN_SHOP: "OPEN_SHOP",
    CLOSE_SHOP: "CLOSE_SHOP",

    BUY_ITEM: "BUY_ITEM",
    SELL_ITEM: "SELL_ITEM",

    ADD_ITEM: "ADD_ITEM",
    REMOVE_ITEM: "REMOVE_ITEM",

    ADD_QUEST: "ADD_QUEST",
    COMPLETE_QUEST: "COMPLETE_QUEST",

    LEVEL_UP: "LEVEL_UP",

    HEAL_PLAYER: "HEAL_PLAYER",

    OPEN_STATUS: "OPEN_STATUS",
    CLOSE_STATUS: "CLOSE_STATUS",


    OPEN_NPC: "OPEN_NPC",
    NPC_ACCEPT: "NPC_ACCEPT",
    NPC_DECLINE: "NPC_DECLINE",

}